# Merge daily data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
uploaded = files.upload()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Saving maabarot_johnson_from_2010_04_22_to_2020_12_31.csv to maabarot_johnson_from_2010_04_22_to_2020_12_31 (1).csv

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')
from google.colab import files
uploaded2 = files.upload()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Saving cl_sample_dataset.csv to cl_sample_dataset (1).csv

In [ ]:
#Load in solar data
import pandas as pd 
import io
johnson = pd.read_csv(io.BytesIO(uploaded['maabarot_johnson_from_2010_04_22_to_2020_12_31.csv']))
johnson.head(17) #visualize data

              timestamp  min_power  mean_power  max_power
0   2010-04-22 01:00:00          0           0          0
1   2010-04-22 02:00:00          0           0          0
2   2010-04-22 03:00:00          0           0          0
3   2010-04-22 04:00:00          0           0          0
4   2010-04-22 05:00:00          0           0          0
5   2010-04-22 06:00:00          0           0          0
6   2010-04-22 07:00:00          0           0          0
7   2010-04-22 08:00:00          0           0          0
8   2010-04-22 09:00:00          0           0          0
9   2010-04-22 10:00:00          0           0          0
10  2010-04-22 11:00:00          0           0          0
11  2010-04-22 12:00:00          0           0          0
12  2010-04-22 13:00:00          0           0          0
13  2010-04-22 14:00:00          0           0          0
14  2010-04-22 15:00:00          0           0          0
15  2010-04-22 16:00:00      36830       38520      40180
16  2010-04-22 17:00:00      19500       21130      22790

In [ ]:
type(johnson.timestamp[0])
#johnson.timestamp = pd.to_datetime(johnson.timestamp)
#johnson.resample('D').sum()

str

In [ ]:
#Load in carbon price data
import pandas as pd 
import io
cl = pd.read_csv(io.BytesIO(uploaded2['cl_sample_dataset.csv']))
cl.tail() #visualize data
cl

,date,place,open,close,high,low,change,pct_chg,vol,amount
0,20210831,GDEA,38.74,39.89,39.98,38.22,1.15,2.97,52780,2105186.21
1,20210830,GDEA,39.70,38.74,40,37.7,-0.96,-2.42,51372,1938146.70
2,20210827,GDEA,38.05,39.70,39.7,38.99,1.65,4.34,50330,1997869.20
3,20210826,GDEA,39.28,38.05,41.48,37.5,-1.23,-3.13,59124,2222257.12
4,20210825,GDEA,38.11,39.28,39.48,37.89,1.17,3.07,58836,2311096.13
...,...,...,...,...,...,...,...,...,...,...
1595,20140320,GDEA,66.00,65.00,65,65,-1.00,-1.52,6,390.00
1596,20140319,GDEA,65.00,66.00,66,66,1.00,1.54,10,660.00
1597,20140318,GDEA,65.00,65.00,65,65,0.00,0.00,100,6500.00
1598,20140317,GDEA,63.00,65.00,65,65,2.00,3.17,100,6500.00
1599,20140314,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00

In [ ]:
#convert timestamp version of column ("date") to "timestamp"
cl['timestamp'] = pd.to_datetime(cl['date'].astype(str), format='%Y%m%d') 
cl.drop('date', inplace=True, axis=1)
cl

,place,open,close,high,low,change,pct_chg,vol,amount,timestamp
0,GDEA,38.74,39.89,39.98,38.22,1.15,2.97,52780,2105186.21,2021-08-31
1,GDEA,39.70,38.74,40,37.7,-0.96,-2.42,51372,1938146.70,2021-08-30
2,GDEA,38.05,39.70,39.7,38.99,1.65,4.34,50330,1997869.20,2021-08-27
3,GDEA,39.28,38.05,41.48,37.5,-1.23,-3.13,59124,2222257.12,2021-08-26
4,GDEA,38.11,39.28,39.48,37.89,1.17,3.07,58836,2311096.13,2021-08-25
...,...,...,...,...,...,...,...,...,...,...
1595,GDEA,66.00,65.00,65,65,-1.00,-1.52,6,390.00,2014-03-20
1596,GDEA,65.00,66.00,66,66,1.00,1.54,10,660.00,2014-03-19
1597,GDEA,65.00,65.00,65,65,0.00,0.00,100,6500.00,2014-03-18
1598,GDEA,63.00,65.00,65,65,2.00,3.17,100,6500.00,2014-03-17
1599,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,2014-03-14

In [ ]:
johnson['timestamp'] = pd.to_datetime(johnson['timestamp'])
johnson_daily = johnson.resample('D', on ='timestamp').sum()
johnson_daily.to_csv(r'\Users\alexgoldschmidt\Desktop\johnson_daily.csv')
johnson_daily = pd.read_csv(r'\Users\alexgoldschmidt\Desktop\johnson_daily.csv')
johnson_daily

       timestamp  min_power  mean_power  max_power
0     2010-04-22      65510       76530      88960
1     2010-04-23     269700      337230     404090
2     2010-04-24     321950      360690     400330
3     2010-04-25     312630      357470     400340
4     2010-04-26     323040      357890     395680
...          ...        ...         ...        ...
3902  2020-12-27     127630      149514     169708
3903  2020-12-28     118519      138870     157003
3904  2020-12-29     122460      144673     164584
3905  2020-12-30     124449      143195     161443
3906  2020-12-31     112944      133648     153129

[3907 rows x 4 columns]

In [ ]:
johnson_daily['timestamp'] = pd.to_datetime(johnson_daily['timestamp'])
merged = cl.set_index('timestamp').join(johnson_daily.set_index('timestamp'), how='left')
print(merged)
#johnson dates = 2010-04-22 - 2020-12-31
#cl dates = 2014-03-14 - 2021-08-31
type(cl.timestamp[0]) #pandas._libs.tslibs.timestamps.Timestamp
type(johnson_daily.timestamp[0]) # str --> pandas._libs.tslibs.timestamps.Timestamp

           place   open  close   high    low  change  pct_chg    vol  \
timestamp
2021-08-31  GDEA  38.74  39.89  39.98  38.22    1.15     2.97  52780
2021-08-30  GDEA  39.70  38.74     40   37.7   -0.96    -2.42  51372
2021-08-27  GDEA  38.05  39.70   39.7  38.99    1.65     4.34  50330
2021-08-26  GDEA  39.28  38.05  41.48   37.5   -1.23    -3.13  59124
2021-08-25  GDEA  38.11  39.28  39.48  37.89    1.17     3.07  58836
...          ...    ...    ...    ...    ...     ...      ...    ...
2014-03-20  GDEA  66.00  65.00     65     65   -1.00    -1.52      6
2014-03-19  GDEA  65.00  66.00     66     66    1.00     1.54     10
2014-03-18  GDEA  65.00  65.00     65     65    0.00     0.00    100
2014-03-17  GDEA  63.00  65.00     65     65    2.00     3.17    100
2014-03-14  GDEA  60.00  63.00     63     63    3.00     5.00    200

                amount  min_power  mean_power  max_power
timestamp
2021-08-31  2105186.21        NaN         NaN        NaN
2021-08-30  1938146.70        NaN         NaN        NaN
2021-08-27  1997869.20        NaN         NaN        NaN
2021-08-26  2222257.12        NaN         NaN        NaN
2021-08-25  2311096.13        NaN         NaN        NaN
...                ...        ...         ...        ...
2014-03-20      390.00   250728.0    281408.0   311301.0
2014-03-19      660.00   249340.0    280531.0   311901.0
2014-03-18     6500.00   126007.0    175892.0   230673.0
2014-03-17     6500.00    57601.0     77135.0   101315.0
2014-03-14    12600.00    87709.0    177635.0   255022.0

[1600 rows x 12 columns]

pandas._libs.tslibs.timestamps.Timestamp

# Data Cleaning (DAILY DATA)

In [ ]:
merge_final = pd.merge(cl, johnson_daily, left_on = 'timestamp', right_on = 'timestamp')
merge_final

,place,open,close,high,low,change,pct_chg,vol,amount,timestamp,min_power,mean_power,max_power
0,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,2020-12-31,112944,133648,153129
1,GDEA,28.24,28.37,28.87,28.36,0.13,0.46,21968,623271.56,2020-12-30,124449,143195,161443
2,GDEA,28.88,28.24,28.87,26.5,-0.64,-2.22,13361,376389.07,2020-12-29,122460,144673,164584
3,GDEA,28.85,28.88,28.88,26.4,0.03,0.10,1050,28960.00,2020-12-28,118519,138870,157003
4,GDEA,28.39,28.85,28.88,26,0.46,1.62,309044,8448852.00,2020-12-25,129174,148606,167553
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,GDEA,66.00,65.00,65,65,-1.00,-1.52,6,390.00,2014-03-20,250728,281408,311301
1430,GDEA,65.00,66.00,66,66,1.00,1.54,10,660.00,2014-03-19,249340,280531,311901
1431,GDEA,65.00,65.00,65,65,0.00,0.00,100,6500.00,2014-03-18,126007,175892,230673
1432,GDEA,63.00,65.00,65,65,2.00,3.17,100,6500.00,2014-03-17,57601,77135,101315
1433,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,2014-03-14,87709,177635,255022

In [ ]:
merge_final.dtypes
merge_final.describe()
merge_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1434 entries, 0 to 1433
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   place       1434 non-null   object
 1   open        1434 non-null   float64
 2   close       1434 non-null   float64
 3   high        1434 non-null   object
 4   low         1434 non-null   object
 5   change      1434 non-null   float64
 6   pct_chg     1434 non-null   float64
 7   vol         1434 non-null   int64
 8   amount      1434 non-null   float64
 9   timestamp   1434 non-null   datetime64[ns]
 10  min_power   1434 non-null   int64
 11  mean_power  1434 non-null   int64
 12  max_power   1434 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(4), object(3)
memory usage: 156.8+ KB

In [ ]:
print(type(merge_final['timestamp'][0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [ ]:
merge_final['timestamp'] = pd.to_datetime(merge_final['timestamp'])
merge_final['timestamp']

0      2020-12-31
1      2020-12-30
2      2020-12-29
3      2020-12-28
4      2020-12-25
          ...
1429   2014-03-20
1430   2014-03-19
1431   2014-03-18
1432   2014-03-17
1433   2014-03-14
Name: timestamp, Length: 1434, dtype: datetime64[ns]

In [ ]:
print(merge_final)

     place   open  close   high    low  change  pct_chg     vol       amount  \
0     GDEA  28.37  28.41  28.89     26    0.04     0.14  565105  15834782.89
1     GDEA  28.24  28.37  28.87  28.36    0.13     0.46   21968    623271.56
2     GDEA  28.88  28.24  28.87   26.5   -0.64    -2.22   13361    376389.07
3     GDEA  28.85  28.88  28.88   26.4    0.03     0.10    1050     28960.00
4     GDEA  28.39  28.85  28.88     26    0.46     1.62  309044   8448852.00
...    ...    ...    ...    ...    ...     ...      ...     ...          ...
1429  GDEA  66.00  65.00     65     65   -1.00    -1.52       6       390.00
1430  GDEA  65.00  66.00     66     66    1.00     1.54      10       660.00
1431  GDEA  65.00  65.00     65     65    0.00     0.00     100      6500.00
1432  GDEA  63.00  65.00     65     65    2.00     3.17     100      6500.00
1433  GDEA  60.00  63.00     63     63    3.00     5.00     200     12600.00

      timestamp  min_power  mean_power  max_power
0    2020-12-31     112944      133648     153129
1    2020-12-30     124449      143195     161443
2    2020-12-29     122460      144673     164584
3    2020-12-28     118519      138870     157003
4    2020-12-25     129174      148606     167553
...         ...        ...         ...        ...
1429 2014-03-20     250728      281408     311301
1430 2014-03-19     249340      280531     311901
1431 2014-03-18     126007      175892     230673
1432 2014-03-17      57601       77135     101315
1433 2014-03-14      87709      177635     255022

[1434 rows x 13 columns]

In [ ]:
value = merge_final.isnull().values.any()
print(value)

False

In [ ]:
!pip install pandasql
import pandasql as ps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.37)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.11.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.2)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26784 sha256=769f4ed9816138666b5ebaeb78e4203f47d4cee216c5081776ac2a915b16484d
  Stored in directory: /root/.cache/pip/wheels/5c/4b/ec/41f4e116c8053c3654e2c2a47c62b4fca34cc67ef7b55deb7f
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [ ]:
query2 = """SELECT AVG(mean_power) FROM merge_final GROUP BY TIME(timestamp)"""
answer_avg = ps.sqldf(query2, locals())

In [ ]:
answer_avg = answer_avg.rename(columns={'AVG(mean_power)': 'Average Mean Power'})

# Merge hourly data

In [ ]:
johnson

                timestamp  min_power  mean_power  max_power
0     2010-04-22 01:00:00          0           0          0
1     2010-04-22 02:00:00          0           0          0
2     2010-04-22 03:00:00          0           0          0
3     2010-04-22 04:00:00          0           0          0
4     2010-04-22 05:00:00          0           0          0
...                   ...        ...         ...        ...
92899 2020-12-31 20:00:00          0           0          0
92900 2020-12-31 21:00:00          0           0          0
92901 2020-12-31 22:00:00          0           0          0
92902 2020-12-31 23:00:00          0           0          0
92903 2020-12-31 00:00:00          0           0          0

[92904 rows x 4 columns]

In [ ]:
cl.tail()

          date place  open  close high low  change  pct_chg  vol   amount
1595  20140320  GDEA  66.0   65.0   65  65    -1.0    -1.52    6    390.0
1596  20140319  GDEA  65.0   66.0   66  66     1.0     1.54   10    660.0
1597  20140318  GDEA  65.0   65.0   65  65     0.0     0.00  100   6500.0
1598  20140317  GDEA  63.0   65.0   65  65     2.0     3.17  100   6500.0
1599  20140314  GDEA  60.0   63.0   63  63     3.0     5.00  200  12600.0

In [ ]:
#convert timestamp version of column ("date") to "timestamp"
cl['timestamp'] = pd.to_datetime(cl['date'].astype(str), format='%Y%m%d') 
cl.drop('date', inplace=True, axis=1)
cl_hourly = cl.set_index("timestamp").resample("H").ffill().reset_index().rename(
    {"timestamp": "timestamp"}, axis=1
)

In [ ]:
cl_hourly.head(200)

,timestamp,place,open,close,high,low,change,pct_chg,vol,amount
0,2014-03-14 00:00:00,GDEA,60.0,63.0,63,63,3.0,5.00,200,12600.0
1,2014-03-14 01:00:00,GDEA,60.0,63.0,63,63,3.0,5.00,200,12600.0
2,2014-03-14 02:00:00,GDEA,60.0,63.0,63,63,3.0,5.00,200,12600.0
3,2014-03-14 03:00:00,GDEA,60.0,63.0,63,63,3.0,5.00,200,12600.0
4,2014-03-14 04:00:00,GDEA,60.0,63.0,63,63,3.0,5.00,200,12600.0
...,...,...,...,...,...,...,...,...,...,...
195,2014-03-22 03:00:00,GDEA,65.0,63.0,63,63,-2.0,-3.08,48,3024.0
196,2014-03-22 04:00:00,GDEA,65.0,63.0,63,63,-2.0,-3.08,48,3024.0
197,2014-03-22 05:00:00,GDEA,65.0,63.0,63,63,-2.0,-3.08,48,3024.0
198,2014-03-22 06:00:00,GDEA,65.0,63.0,63,63,-2.0,-3.08,48,3024.0
199,2014-03-22 07:00:00,GDEA,65.0,63.0,63,63,-2.0,-3.08,48,3024.0

In [ ]:
value2 = cl_hourly.isnull().values.any()
print(value2)

False

In [ ]:
mergeHourly = pd.merge(cl_hourly, johnson, left_on = 'timestamp', right_on = 'timestamp')
mergeHourly

,timestamp,place,open,close,high,low,change,pct_chg,vol,amount,min_power,mean_power,max_power
0,2014-03-14 00:00:00,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
1,2014-03-14 01:00:00,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
2,2014-03-14 02:00:00,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
3,2014-03-14 03:00:00,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
4,2014-03-14 04:00:00,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58771,2020-12-31 19:00:00,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
58772,2020-12-31 20:00:00,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
58773,2020-12-31 21:00:00,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
58774,2020-12-31 22:00:00,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
58775,2020-12-31 23:00:00,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0

In [ ]:
mergeHourly_null = mergeHourly.isnull().values.any()
print(mergeHourly_null )

False

# Data Cleaning (HOURLY DATA)

In [ ]:
print(type(mergeHourly['timestamp'][0]))
print(mergeHourly)
mergeHourly.dtypes

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
                timestamp place   open  close   high low  change  pct_chg  \
0     2014-03-14 00:00:00  GDEA  60.00  63.00     63  63    3.00     5.00
1     2014-03-14 01:00:00  GDEA  60.00  63.00     63  63    3.00     5.00
2     2014-03-14 02:00:00  GDEA  60.00  63.00     63  63    3.00     5.00
3     2014-03-14 03:00:00  GDEA  60.00  63.00     63  63    3.00     5.00
4     2014-03-14 04:00:00  GDEA  60.00  63.00     63  63    3.00     5.00
...                   ...   ...    ...    ...    ...  ..     ...      ...
58771 2020-12-31 19:00:00  GDEA  28.37  28.41  28.89  26    0.04     0.14
58772 2020-12-31 20:00:00  GDEA  28.37  28.41  28.89  26    0.04     0.14
58773 2020-12-31 21:00:00  GDEA  28.37  28.41  28.89  26    0.04     0.14
58774 2020-12-31 22:00:00  GDEA  28.37  28.41  28.89  26    0.04     0.14
58775 2020-12-31 23:00:00  GDEA  28.37  28.41  28.89  26    0.04     0.14

          vol       amount  min_power  mean_power  max_power
0         200     12600.00          0           0          0
1         200     12600.00          0           0          0
2         200     12600.00          0           0          0
3         200     12600.00          0           0          0
4         200     12600.00          0           0          0
...       ...          ...        ...         ...        ...
58771  565105  15834782.89          0           0          0
58772  565105  15834782.89          0           0          0
58773  565105  15834782.89          0           0          0
58774  565105  15834782.89          0           0          0
58775  565105  15834782.89          0           0          0

[58776 rows x 13 columns]

timestamp     datetime64[ns]
place                 object
open                 float64
close                float64
high                  object
low                   object
change               float64
pct_chg              float64
vol                    int64
amount               float64
min_power              int64
mean_power             int64
max_power              int64
dtype: object

In [ ]:
new_df = mergeHourly

In [ ]:
query = """SELECT * FROM new_df WHERE TIME(timestamp) BETWEEN TIME('05:00:00') AND TIME('19:00:00') AND mean_power = 0"""
zero_df = ps.sqldf(query, locals())
zero_df

,timestamp,place,open,close,high,low,change,pct_chg,vol,amount,min_power,mean_power,max_power
0,2014-03-14 05:00:00.000000,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
1,2014-03-14 06:00:00.000000,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
2,2014-03-14 07:00:00.000000,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
3,2014-03-14 19:00:00.000000,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
4,2014-03-15 05:00:00.000000,GDEA,60.00,63.00,63,63,3.00,5.00,200,12600.00,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7160,2020-12-31 05:00:00.000000,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
7161,2020-12-31 06:00:00.000000,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
7162,2020-12-31 07:00:00.000000,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
7163,2020-12-31 18:00:00.000000,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0
7164,2020-12-31 19:00:00.000000,GDEA,28.37,28.41,28.89,26,0.04,0.14,565105,15834782.89,0,0,0

In [ ]:
zero_df['timestamp'] = pd.to_datetime(zero_df['timestamp'])
zero_df['timestamp']

0      2014-03-14 05:00:00
1      2014-03-14 06:00:00
2      2014-03-14 07:00:00
3      2014-03-14 19:00:00
4      2014-03-15 05:00:00
               ...
7160   2020-12-31 05:00:00
7161   2020-12-31 06:00:00
7162   2020-12-31 07:00:00
7163   2020-12-31 18:00:00
7164   2020-12-31 19:00:00
Name: timestamp, Length: 7165, dtype: datetime64[ns]

In [ ]:
query2 = """SELECT AVG(mean_power) FROM new_df GROUP BY TIME(timestamp)"""
answer_avg = ps.sqldf(query2, locals())
answer_avg

    AVG(mean_power)
0          0.000000
1          0.000000
2          0.000000
3          0.000000
4          0.000000
5          0.000408
6          1.872601
7        445.502246
8       3892.271539
9      11003.681094
10     18250.318906
11     24510.336464
12     28620.007758
13     30264.224990
14     29338.027358
15     25825.191915
16     19770.488771
17     12391.945284
18      6275.735402
19      1980.144957
20       203.623928
21         0.000000
22         0.000000
23         0.000000

In [ ]:
answer_avg = answer_avg.rename(columns={'AVG(mean_power)': 'Average Mean Power'})
answer_avg.index.names = ['Timestamp']
answer_avg

           Average Mean Power
Timestamp
0                    0.000000
1                    0.000000
2                    0.000000
3                    0.000000
4                    0.000000
5                    0.000408
6                    1.872601
7                  445.502246
8                 3892.271539
9                11003.681094
10               18250.318906
11               24510.336464
12               28620.007758
13               30264.224990
14               29338.027358
15               25825.191915
16               19770.488771
17               12391.945284
18                6275.735402
19                1980.144957
20                 203.623928
21                   0.000000
22                   0.000000
23                   0.000000

In [ ]:
std_df = new_df.groupby([new_df['timestamp'].dt.time])['mean_power'].std()
std_df

timestamp
00:00:00        0.000000
01:00:00        0.000000
02:00:00        0.000000
03:00:00        0.000000
04:00:00        0.000000
05:00:00        0.020207
06:00:00       38.370838
07:00:00      549.241834
08:00:00     2405.493212
09:00:00     4481.088063
10:00:00     6242.920886
11:00:00     7580.560903
12:00:00     8778.201795
13:00:00     9469.633555
14:00:00     9729.865114
15:00:00    10136.857769
16:00:00    10434.613714
17:00:00     9567.638405
18:00:00     6237.565099
19:00:00     2255.850928
20:00:00      313.978019
21:00:00        0.000000
22:00:00        0.000000
23:00:00        0.000000
Name: mean_power, dtype: float64

In [ ]:
std_list = []
for i in std_df:
    if str(i) == 'nan':
        i = 0.0
    std_list.append(float(i/1000))
std_list
#gets rid of NaN values/go back 2 decimal places (even though there are not null values present).

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0207175225248877e-05,
 0.03837083763981522,
 0.5492418341835767,
 2.4054932118994627,
 4.4810880626766885,
 6.242920886183796,
 7.580560902513289,
 8.778201795272084,
 9.469633554842707,
 9.729865114182363,
 10.136857769116164,
 10.43461371430711,
 9.567638405476698,
 6.237565099027027,
 2.2558509279484538,
 0.3139780188786711,
 0.0,
 0.0,
 0.0]

# CEEMDAN

In [ ]:
import numpy as np

shape3 = mergeHourly.shape
print('\nDataFrame Shape :', shape3)
print('\nNumber of rows :', shape3[0])
print('\nNumber of columns :', shape3[1])

DataFrame Shape : (58776, 13)

Number of rows : 58776

Number of columns : 13

In [ ]:
!pip install EMD-signal
from PyEMD import EMD,EEMD,CEEMDAN
!pip install sampen
!pip install vmdpy
!pip install datetime
!pip install tensorflow-gpu==2.5.0
!pip install scikit-learn

!python CEEMDAN_LSTM.py

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting EMD-signal
  Downloading EMD_signal-1.2.3-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.1 MB/s
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.7/dist-packages (from EMD-signal) (1.4.1)
Collecting pathos>=0.2.1
  Downloading pathos-0.2.9-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 5.0 MB/s
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python3.7/dist-packages (from EMD-signal) (1.21.6)
Collecting ppft>=1.7.6.5
  Downloading ppft-1.7.6.5-py2.py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 357 kB/s
Collecting pox>=0.3.1
  Downloading pox-0.3.1-py2.py3-none-any.whl (28 kB)
Requirement already satisfied: multiprocess>=0.70.13 in /usr/local/lib/python3.7/dist-packages (from pathos>=0.2.1->EMD-signal) (0.70.13)
Requirement already satisfied: dill>=0.3.5.1 in /usr/local/lib/python3.7/dist-packages (from pathos>=0.2.1->EMD-signal) (0.3.5.1)
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python3.7/dist-packages (from ppft>=1.7.6.5->pathos>=0.2.1->EMD-signal) (1.15.0)
Installing collected packages: ppft, pox, pathos, EMD-signal
Successfully installed EMD-signal-1.2.3 pathos-0.2.9 pox-0.3.1 ppft-1.7.6.5
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sampen
  Downloading sampen-0.0.17-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy>=1.9.2 in /usr/local/lib/python3.7/dist-packages (from sampen) (1.21.6)
Installing collected packages: sampen
Successfully installed sampen-0.0.17
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vmdpy
  Downloading vmdpy-0.2-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from vmdpy) (1.21.6)
Installing collected packages: vmdpy
Successfully installed vmdpy-0.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting datetime
  Downloading DateTime-4.4-py2.py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB 404 kB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from datetime) (2022.1)
Collecting zope.interface
  Downloading zope.interface-5.4.0-cp37-cp37m-manylinux2010_x86_64.whl (251 kB)
     |████████████████████████████████| 251 kB 9.6 MB/s
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from zope.interface->datetime) (57.4.0)
Installing collected packages: zope.interface, datetime
Successfully installed datetime-4.4 zope.interface-5.4.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tensorflow-gpu==2.5.0
  Downloading tensorflow_gpu-2.5.0-cp37-cp37m-manylinux2010_x86_64.whl (454.3 MB)
     |████████████████████████████████| 454.3 MB 12 kB/s
Collecting keras-nightly~=2.5.0.dev
  Downloading keras_nightly-2.5.0.dev2021032900-py2.py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 47.5 MB/s
Requirement already satisfied: tensorboard~=2.5 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (2.8.0)
Collecting typing-extensions~=3.7.4
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting flatbuffers~=1.12.0
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: six~=1.15.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (1.15.0)
Requirement already satisfied: opt-einsum~=3.3.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (3.3.0)
Requirement already satisfied: termcolor~=1.1.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (1.1.0)
Requirement already satisfied: astunparse~=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (1.6.3)
Requirement already satisfied: protobuf>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (3.17.3)
Collecting numpy~=1.19.2
  Downloading numpy-1.19.5-cp37-cp37m-manylinux2010_x86_64.whl (14.8 MB)
     |████████████████████████████████| 14.8 MB 33.6 MB/s
Collecting tensorflow-estimator<2.6.0,>=2.5.0rc0
  Downloading tensorflow_estimator-2.5.0-py2.py3-none-any.whl (462 kB)
     |████████████████████████████████| 462 kB 53.7 MB/s
Collecting wrapt~=1.12.1
  Downloading wrapt-1.12.1.tar.gz (27 kB)
Requirement already satisfied: google-pasta~=0.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (0.2.0)
Requirement already satisfied: keras-preprocessing~=1.1.2 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (1.1.2)
Requirement already satisfied: wheel~=0.35 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (0.37.1)
Collecting gast==0.4.0
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting grpcio~=1.34.0
  Downloading grpcio-1.34.1-cp37-cp37m-manylinux2014_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 43.0 MB/s
Requirement already satisfied: h5py~=3.1.0 in /usr/local/lib/python3.7/dist-packages (from tensorflow-gpu==2.5.0) (3.1.0)
Collecting absl-py~=0.10
  Downloading absl_py-0.15.0-py3-none-any.whl (132 kB)
     |████████████████████████████████| 132 kB 48.5 MB/s
Requirement already satisfied: cached-property in /usr/local/lib/python3.7/dist-packages (from h5py~=3.1.0->tensorflow-gpu==2.5.0) (1.5.2)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (1.8.1)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (2.23.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (1.0.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (0.4.6)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (57.4.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (1.35.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (3.3.7)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard~=2.5->tensorflow-gpu==2.5.0) (0.6.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard~=2.5->tensorflow-gpu==2.5.0) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard~=2.5->tensorflow-gpu==2.5.0) (4.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard~=2.5->tensorflow-gpu==2.5.0) (4.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow-gpu==2.5.0) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from markdown>=2.6.8->tensorboard~=2.5->tensorflow-gpu==2.5.0) (4.11.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard~=2.5->tensorflow-gpu==2.5.0) (3.8.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.5->tensorflow-gpu==2.5.0) (0.4.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow-gpu==2.5.0) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow-gpu==2.5.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow-gpu==2.5.0) (2022.6.15)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.21.0->tensorboard~=2.5->tensorflow-gpu==2.5.0) (2.10)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.5->tensorflow-gpu==2.5.0) (3.2.0)
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py) ... done
  Created wheel for wrapt: filename=wrapt-1.12.1-cp37-cp37m-linux_x86_64.whl size=68719 sha256=db3c2af30d444ebbdedd673a6e0bbfa2fd3de31bf6cb8afda87bd96daa2c849d
  Stored in directory: /root/.cache/pip/wheels/62/76/4c/aa25851149f3f6d9785f6c869387ad82b3fd37582fa8147ac6
Successfully built wrapt
Installing collected packages: typing-extensions, numpy, grpcio, absl-py, wrapt, tensorflow-estimator, keras-nightly, gast, flatbuffers, tensorflow-gpu
  Attempting uninstall: typing-extensions
    Found existing installation: typing-extensions 4.1.1
    Uninstalling typing-extensions-4.1.1:
      Successfully uninstalled typing-extensions-4.1.1
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.46.3
    Uninstalling grpcio-1.46.3:
      Successfully uninstalled grpcio-1.46.3
  Attempting uninstall: absl-py
    Found existing installation: absl-py 1.1.0
    Uninstalling absl-py-1.1.0:
      Successfully uninstalled absl-py-1.1.0
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.14.1
    Uninstalling wrapt-1.14.1:
      Successfully uninstalled wrapt-1.14.1
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5.3
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 2.0
    Uninstalling flatbuffers-2.0:
      Successfully uninstalled flatbuffers-2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.2.2 requires numpy>=1.21, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
tensorflow 2.8.2+zzzcolab20220527125636 requires tensorflow-estimator<2.9,>=2.8, but you have tensorflow-estimator 2.5.0 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed absl-py-0.15.0 flatbuffers-1.12 gast-0.4.0 grpcio-1.34.1 keras-nightly-2.5.0.dev2021032900 numpy-1.19.5 tensorflow-estimator-2.5.0 tensorflow-gpu-2.5.0 typing-extensions-3.7.4.3 wrapt-1.12.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.4.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.19.5)
python3: can't open file 'CEEMDAN_LSTM.py': [Errno 2] No such file or directory

In [ ]:
!python CEEMDAN_LSTM.py
import CEEMDAN_LSTM as cl

2022-07-03 07:03:09.089742: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Importing...Finished. Use cl.guideline() to call for a guideline or cl.example() for an exmple.
An example of cl.example() is running around 1000 seconds.
##################################

(1) Declare a path for saving files:
-------------------------------
Saving path: D:\CEEMDAN_LSTM\
Traceback (most recent call last):
  File "CEEMDAN_LSTM.py", line 1610, in <module>
    run_example()
  File "CEEMDAN_LSTM.py", line 206, in run_example
    series = declare_path()
  File "CEEMDAN_LSTM.py", line 291, in declare_path
    if not isinstance(series, pd.Series): raise ValueError('The inputting series must be pd.Series.')
ValueError: The inputting series must be pd.Series.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
import CEEMDAN_LSTM as cl

In [ ]:
cl.example()

Start your first prediction by following steps:
check your dataset and use cl.run_example() can directly run the following example around 1000 seconds.
##################################
(0) Import:
    import CEEMDAN_LSTM as cl
(1) Declare a path for saving files:
    series = cl.declare_path()
(2) CEEMDAN decompose:
    cl.declare_vars(mode='ceemdan') # set decomposition method
    imfs = cl.emd_decom()
(3) Sample Entropy:
    cl.sample_entropy()
(4) Integrating IMFs:
    cl.integrate(inte_form=[[0,1],[2,3,4],[5,6,7]]) # form 233
(5) Forecast:
    cl.declare_vars(mode='ceemdan_se',form='233',epochs=100) # declare variables for forecast
    cl.Hybrid_LSTM(redecom='vmd') # ceemdan_se233_data.csv
Also you can try other methods such as:
    cl.statistical_tests()
    cl.Single_LSTM()
    cl.Ensemble_LSTM()
    cl.Respective_LSTM()

In [ ]:
PATH = 'D:\\CEEMDAN_LSTM\\'
F_PATH = 'D:\\CEEMDAN_LSTM\\figures\\'
L_PATH = 'D:\\CEEMDAN_LSTM\\subset\\'

In [ ]:
from numpy.core.fromnumeric import clip
#print(type(pd.Series()))

series = pd.Series("D:\\CEEMDAN_LSTM\\cl_sample_dataset.csv")
#series = cl.declare_path(pd.Series('D:\\CEEMDAN_LSTM\\'))
PATH = 'D:\\CEEMDAN_LSTM\\'
F_PATH = 'D:\\CEEMDAN_LSTM\\figures\\'
L_PATH = 'D:\\CEEMDAN_LSTM\\subset\\'
print(series)

0    D:\CEEMDAN_LSTM\cl_sample_dataset.csv
dtype: object